use hector;
insert into host_group (host_group_id,host_group_name) values ("1","Web servers");
insert into host_group (host_group_id,host_group_name) values ("2","Critical hosts");
insert into host_group (host_group_id,host_group_name) values ("6","Machines of interest");
insert into host_group (host_group_id,host_group_name) values ("8","Remote desktop test group");
insert into host_group (host_group_id,host_group_name) values ("9","Testing machines (for debugging)");
insert into host_group (host_group_id,host_group_name) values ("10","All hosts");
insert into host_group (host_group_id,host_group_name) values ("11","Chemistry machines");
insert into host_group (host_group_id,host_group_name) values ("95","New music machines");
insert into host_group (host_group_id,host_group_name) values ("96","New biology machines");
insert into host_group (host_group_id,host_group_name) values ("105","Psychology");
insert into host_group (host_group_id,host_group_name) values ("272","Don't scan");
insert into host_group (host_group_id,host_group_name) values ("474","old_hosts");