#!/bin/sh
#
# hector-ossec-mysql    This starts and stops the HECTOR database logging from OSSEC.
#
# Add this with 'chkconfig --add hector-ossec-mysql' after it's in /etc/init.d
#
# chkconfig:   345 75 25
# description: This starts and stops the HECTOR database logging from OSSEC.
# processname: /opt/hector/app/scripts/hector-ossec-mysql.py
# config:      /opt/hector/app/conf/config.ini
# pidfile:     /var/run/hector-ossec-mysql.pid
#
### BEGIN INIT INFO
# Provides: $hector-ossec-mysql
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

EXEC="/opt/hector/app/scripts/hector-ossec-mysql.py"
PROG=$(basename $EXEC)
RETVAL=0
LOCKFILE=/var/lock/subsys/$PROG
PIDFILE=/var/run/hector-ossec-mysql.pid

start() {    echo -n $"Starting $PROG: "
    daemon $EXEC start
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $LOCKFILE
}

stop() {
    echo -n $"Stopping $PROG: "
    killproc $PROG
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $LOCKFILE $PIDFILE
}

restart() {
    stop
    start
}

fdr_status() {    
    status $PROG
}

case "$1" in
    start|stop|restart)
        $1
        ;;
    status)
        fdr_status
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|try-restart|reload|force-reload}"
        exit 2
esac

exit $RETVAL



