#! /bin/sh
#
# ossec2hector           This shell script enables daemon monitoring of OSSEC logs
#
# Author:       Justin C. Klein Keane <jukeane@sas.upenn.edu>
#
# Add this with 'chkconfig --add ossec2hector' after it's in /etc/init.d
#
# chkconfig:    345 50 01
#
# description:  Enable monitoring of OSSEC logs and import to HECTOR MySQL database
# processname:  ossec2hector
# config:      /etc/ossec2mysql.conf
# pidfile:     /var/run/ossec2hector.pid
#
### BEGIN INIT INFO
# Provides: $ossec2hector
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

EXEC="/opt/hector/app/scripts/ossec2mysqld.pl"
PROG=$(basename $EXEC)
RETVAL=0
LOCKFILE=/var/lock/subsys/$PROG
PIDFILE=/var/run/ossec2hector.pid
set -e
dump=0

test -x /opt/hector/app/scripts/ossec2mysqld.pl || dump=1

if [ $dump -eq 1 ]; then
  echo "${EXEC} not executable, aborting." 
  exit 0
fi

case "$1" in
  start)
        echo -n "Starting HECTOR OSSEC to MySQL import daemon"
        ${EXEC} --conf /etc/ossec2mysql.conf 2>&1 >/dev/null&
        echo "."
  ;;
  stop)
        echo -n "Stopping HECTOR OSSEC to MySQL import daemon"
        kill `ps aux | grep ${EXEC} | grep -v grep | awk '{ print $2 }'`
        echo "."
  ;;

  kill)
        echo -n "Killing HECTOR OSSEC to MySQL import daemon"
        kill -9 `ps aux | grep ${EXEC} | grep -v grep | awk '{ print $2 }'`
        echo "."
  ;;

   restart)
        echo -n "Restarting HECTOR OSSEC to MySQL import daemon"
        /etc/init.d/ossec2hector stop > /dev/null
        /etc/init.d/ossec2hector start > /dev/null
        echo "."
        ;;

  status)
  value=`ps aux | grep /opt/hector/app/scripts/ossec2mysqld.pl | grep -v grep | wc -l`

  if [ $value -eq 0 ]; then
    echo "HECTOR OSSEC to MySQL import daemon server is stopped."
  else
    echo "HECTOR OSSEC to MySQL import daemon server is up and running."
  fi
  ;;
  *)
  echo "Usage: /etc/init.d/ossec2hector {start|stop|kill|restart|status}"
  exit 1
esac

exit 0